// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": {
    "login": "Login",
    "title": {
      "solution": "Solution ",
      "name": "certificate management ",
      "application": "by",
      "description": "Web3 project built on Blockchain platform ensures transparency for certificates"
    },
    "card": {
      "title": "Look up certificates",
      "placeholder": "Enter the certificate number",
      "button": "Search",
      "button_qr_code": "Open camera to scan QR code"
    }
  }
};
export default messages;