// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "home": {
    "title": "Home",
    "welcome": "Welcome to our website!",
    "description": "This is the home page where you can find the latest updates and news.",
    "about": {
      "title": "About",
      "description": "This is the about page where you can find the latest updates and news."
    },
    "name": "Hello {name}"
  }
};
export default messages;